# Generated by Django 2.2.6 on 2020-04-15 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saleor_mp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency_id',
            field=models.CharField(default='ARS', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='insertion_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='net_received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mp_id',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('mp_id', 'date_last_updated')},
        ),
    ]
