# Generated by Django 2.2.6 on 2020-04-15 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0076_auto_20191018_0554'),
        ('saleor_mp', '0002_auto_20200414_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mp_id',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('mp_id', 'order')},
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_refund_id', models.CharField(max_length=60, unique=True)),
                ('date_created', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('mp_payment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='saleor_mp.Payment')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='insertion_time',
        ),
        migrations.CreateModel(
            name='PaymentTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_updated', models.DateTimeField()),
                ('mp_status', models.CharField(blank=True, max_length=60, null=True)),
                ('mp_status_detail', models.CharField(blank=True, max_length=60, null=True)),
                ('currency_id', models.CharField(default='ARS', max_length=3)),
                ('mp_transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insertion_time', models.DateTimeField(auto_now_add=True)),
                ('mp_payment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='trace', to='saleor_mp.Payment')),
            ],
            options={
                'unique_together': {('mp_payment', 'date_last_updated')},
            },
        ),
    ]
