# Generated by Django 2.2.6 on 2020-04-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleor_mp', '0003_auto_20200415_1812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
    ]
